/*
Copyright 2022 Upbound Inc.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type DomainNamesObservation struct {
}

type DomainNamesParameters struct {

	// What action should happen to matching requests. Possible values are: 'Base Policy', 'Allow' or 'Deny'. Defaults to 'Base Policy' if no value is provided.
	// +kubebuilder:validation:Optional
	Action *string `json:"action,omitempty" tf:"action,omitempty"`

	// FQDN.
	// +kubebuilder:validation:Required
	Fqdn *string `json:"fqdn" tf:"fqdn,omitempty"`

	// Port.
	// +kubebuilder:validation:Required
	Port *string `json:"port" tf:"port,omitempty"`

	// Protocol.
	// +kubebuilder:validation:Required
	Proto *string `json:"proto" tf:"proto,omitempty"`
}

type FqdnObservation struct {
	ID *string `json:"id,omitempty" tf:"id,omitempty"`
}

type FqdnParameters struct {

	// A list of one or more domain names/tag rules.
	// +kubebuilder:validation:Optional
	DomainNames []DomainNamesParameters `json:"domainNames,omitempty" tf:"domain_names,omitempty"`

	// FQDN Filter Tag Status. Valid values: true or false.
	// +kubebuilder:validation:Optional
	FqdnEnabled *bool `json:"fqdnEnabled,omitempty" tf:"fqdn_enabled,omitempty"`

	// Specify the tag color to be a white-list tag or black-list tag. 'white' or 'black'
	// +kubebuilder:validation:Optional
	FqdnMode *string `json:"fqdnMode,omitempty" tf:"fqdn_mode,omitempty"`

	// FQDN Filter Tag Name.
	// +kubebuilder:validation:Required
	FqdnTag *string `json:"fqdnTag" tf:"fqdn_tag,omitempty"`

	// A list of gateways to attach to the specific tag.
	// +kubebuilder:validation:Optional
	GwFilterTagList []GwFilterTagListParameters `json:"gwFilterTagList,omitempty" tf:"gw_filter_tag_list,omitempty"`

	// Enable to manage domain name rules in-line. If false, domain name rules must be managed using `aviatrix_fqdn_tag_rule` resources.
	// +kubebuilder:validation:Optional
	ManageDomainNames *bool `json:"manageDomainNames,omitempty" tf:"manage_domain_names,omitempty"`
}

type GwFilterTagListObservation struct {
}

type GwFilterTagListParameters struct {

	// Name of the gateway to attach to the specific tag.
	// +kubebuilder:validation:Required
	GwName *string `json:"gwName" tf:"gw_name,omitempty"`

	// List of source IPs in the VPC qualified for a specific tag.
	// +kubebuilder:validation:Optional
	SourceIPList []*string `json:"sourceIpList,omitempty" tf:"source_ip_list,omitempty"`
}

// FqdnSpec defines the desired state of Fqdn
type FqdnSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     FqdnParameters `json:"forProvider"`
}

// FqdnStatus defines the observed state of Fqdn.
type FqdnStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        FqdnObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true

// Fqdn is the Schema for the Fqdns API. <no value>
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,aviatrix}
type Fqdn struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              FqdnSpec   `json:"spec"`
	Status            FqdnStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// FqdnList contains a list of Fqdns
type FqdnList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Fqdn `json:"items"`
}

// Repository type metadata.
var (
	Fqdn_Kind             = "Fqdn"
	Fqdn_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Fqdn_Kind}.String()
	Fqdn_KindAPIVersion   = Fqdn_Kind + "." + CRDGroupVersion.String()
	Fqdn_GroupVersionKind = CRDGroupVersion.WithKind(Fqdn_Kind)
)

func init() {
	SchemeBuilder.Register(&Fqdn{}, &FqdnList{})
}
