/*
Copyright 2022 Upbound Inc.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type TransitFirenetObservation struct {
	ID *string `json:"id,omitempty" tf:"id,omitempty"`
}

type TransitFirenetParameters struct {

	// Secondary firenet gateway name.
	// +kubebuilder:validation:Required
	SecondaryFirenetGwName *string `json:"secondaryFirenetGwName" tf:"secondary_firenet_gw_name,omitempty"`
}

// TransitFirenetSpec defines the desired state of TransitFirenet
type TransitFirenetSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     TransitFirenetParameters `json:"forProvider"`
}

// TransitFirenetStatus defines the observed state of TransitFirenet.
type TransitFirenetStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        TransitFirenetObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true

// TransitFirenet is the Schema for the TransitFirenets API. <no value>
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,aviatrix}
type TransitFirenet struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              TransitFirenetSpec   `json:"spec"`
	Status            TransitFirenetStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// TransitFirenetList contains a list of TransitFirenets
type TransitFirenetList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []TransitFirenet `json:"items"`
}

// Repository type metadata.
var (
	TransitFirenet_Kind             = "TransitFirenet"
	TransitFirenet_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: TransitFirenet_Kind}.String()
	TransitFirenet_KindAPIVersion   = TransitFirenet_Kind + "." + CRDGroupVersion.String()
	TransitFirenet_GroupVersionKind = CRDGroupVersion.WithKind(TransitFirenet_Kind)
)

func init() {
	SchemeBuilder.Register(&TransitFirenet{}, &TransitFirenetList{})
}
