/*
Copyright 2022 Upbound Inc.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type ConnObservation struct {
	ID *string `json:"id,omitempty" tf:"id,omitempty"`
}

type ConnParameters struct {

	// BGP local ASN (Autonomous System Number). Integer between 1-4294967294.
	// +kubebuilder:validation:Required
	BGPLocalAsNum *string `json:"bgpLocalAsNum" tf:"bgp_local_as_num,omitempty"`

	// Account of AWS's VGW that is used for this connection.
	// +kubebuilder:validation:Required
	BGPVgwAccount *string `json:"bgpVgwAccount" tf:"bgp_vgw_account,omitempty"`

	// Id of AWS's VGW that is used for this connection.
	// +kubebuilder:validation:Required
	BGPVgwID *string `json:"bgpVgwId" tf:"bgp_vgw_id,omitempty"`

	// Region of AWS's VGW that is used for this connection.
	// +kubebuilder:validation:Required
	BGPVgwRegion *string `json:"bgpVgwRegion" tf:"bgp_vgw_region,omitempty"`

	// The name of the VGW connection which is going to be created.
	// +kubebuilder:validation:Required
	ConnName *string `json:"connName" tf:"conn_name,omitempty"`

	// Enable Event Triggered HA.
	// +kubebuilder:validation:Optional
	EnableEventTriggeredHa *bool `json:"enableEventTriggeredHa,omitempty" tf:"enable_event_triggered_ha,omitempty"`

	// Enable learned CIDR approval for the connection. Requires the transit_gateway's 'learned_cidrs_approval_mode' attribute be set to 'connection'. Valid values: true, false. Default value: false. Available as of provider version R2.18+.
	// +kubebuilder:validation:Optional
	EnableLearnedCidrsApproval *bool `json:"enableLearnedCidrsApproval,omitempty" tf:"enable_learned_cidrs_approval,omitempty"`

	// Name of the Transit Gateway.
	// +kubebuilder:validation:Required
	GwName *string `json:"gwName" tf:"gw_name,omitempty"`

	// Configure manual BGP advertised CIDRs for this connection. Available as of provider version R2.18+.
	// +kubebuilder:validation:Optional
	ManualBGPAdvertisedCidrs []*string `json:"manualBgpAdvertisedCidrs,omitempty" tf:"manual_bgp_advertised_cidrs,omitempty"`

	// Connection AS Path Prepend customized by specifying AS PATH for a BGP connection.
	// +kubebuilder:validation:Optional
	PrependAsPath []*string `json:"prependAsPath,omitempty" tf:"prepend_as_path,omitempty"`

	// VPC-ID where the Transit Gateway is located.
	// +kubebuilder:validation:Required
	VPCID *string `json:"vpcId" tf:"vpc_id,omitempty"`
}

// ConnSpec defines the desired state of Conn
type ConnSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     ConnParameters `json:"forProvider"`
}

// ConnStatus defines the observed state of Conn.
type ConnStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        ConnObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true

// Conn is the Schema for the Conns API. <no value>
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,aviatrix}
type Conn struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              ConnSpec   `json:"spec"`
	Status            ConnStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// ConnList contains a list of Conns
type ConnList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Conn `json:"items"`
}

// Repository type metadata.
var (
	Conn_Kind             = "Conn"
	Conn_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Conn_Kind}.String()
	Conn_KindAPIVersion   = Conn_Kind + "." + CRDGroupVersion.String()
	Conn_GroupVersionKind = CRDGroupVersion.WithKind(Conn_Kind)
)

func init() {
	SchemeBuilder.Register(&Conn{}, &ConnList{})
}
