//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2022 Upbound Inc.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Conn) DeepCopyInto(out *Conn) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Conn.
func (in *Conn) DeepCopy() *Conn {
	if in == nil {
		return nil
	}
	out := new(Conn)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Conn) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConnList) DeepCopyInto(out *ConnList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Conn, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConnList.
func (in *ConnList) DeepCopy() *ConnList {
	if in == nil {
		return nil
	}
	out := new(ConnList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ConnList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConnObservation) DeepCopyInto(out *ConnObservation) {
	*out = *in
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConnObservation.
func (in *ConnObservation) DeepCopy() *ConnObservation {
	if in == nil {
		return nil
	}
	out := new(ConnObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConnParameters) DeepCopyInto(out *ConnParameters) {
	*out = *in
	if in.BGPLocalAsNum != nil {
		in, out := &in.BGPLocalAsNum, &out.BGPLocalAsNum
		*out = new(string)
		**out = **in
	}
	if in.BGPVgwAccount != nil {
		in, out := &in.BGPVgwAccount, &out.BGPVgwAccount
		*out = new(string)
		**out = **in
	}
	if in.BGPVgwID != nil {
		in, out := &in.BGPVgwID, &out.BGPVgwID
		*out = new(string)
		**out = **in
	}
	if in.BGPVgwRegion != nil {
		in, out := &in.BGPVgwRegion, &out.BGPVgwRegion
		*out = new(string)
		**out = **in
	}
	if in.ConnName != nil {
		in, out := &in.ConnName, &out.ConnName
		*out = new(string)
		**out = **in
	}
	if in.EnableEventTriggeredHa != nil {
		in, out := &in.EnableEventTriggeredHa, &out.EnableEventTriggeredHa
		*out = new(bool)
		**out = **in
	}
	if in.EnableLearnedCidrsApproval != nil {
		in, out := &in.EnableLearnedCidrsApproval, &out.EnableLearnedCidrsApproval
		*out = new(bool)
		**out = **in
	}
	if in.GwName != nil {
		in, out := &in.GwName, &out.GwName
		*out = new(string)
		**out = **in
	}
	if in.ManualBGPAdvertisedCidrs != nil {
		in, out := &in.ManualBGPAdvertisedCidrs, &out.ManualBGPAdvertisedCidrs
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.PrependAsPath != nil {
		in, out := &in.PrependAsPath, &out.PrependAsPath
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.VPCID != nil {
		in, out := &in.VPCID, &out.VPCID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConnParameters.
func (in *ConnParameters) DeepCopy() *ConnParameters {
	if in == nil {
		return nil
	}
	out := new(ConnParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConnSpec) DeepCopyInto(out *ConnSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConnSpec.
func (in *ConnSpec) DeepCopy() *ConnSpec {
	if in == nil {
		return nil
	}
	out := new(ConnSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConnStatus) DeepCopyInto(out *ConnStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConnStatus.
func (in *ConnStatus) DeepCopy() *ConnStatus {
	if in == nil {
		return nil
	}
	out := new(ConnStatus)
	in.DeepCopyInto(out)
	return out
}
