/*
Copyright 2022 Upbound Inc.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type SyslogObservation struct {
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// True if not protected by TLS.
	Notls *bool `json:"notls,omitempty" tf:"notls,omitempty"`

	// Enabled or not.
	Status *string `json:"status,omitempty" tf:"status,omitempty"`
}

type SyslogParameters struct {

	// CA certificate file.
	// +kubebuilder:validation:Optional
	CACertificateFile *string `json:"caCertificateFile,omitempty" tf:"ca_certificate_file,omitempty"`

	// List of excluded gateways.
	// +kubebuilder:validation:Optional
	ExcludedGateways []*string `json:"excludedGateways,omitempty" tf:"excluded_gateways,omitempty"`

	// A total of 10 profiles from index 0 to 9 are supported for remote syslog, while index 9 is reserved for CoPilot.
	// +kubebuilder:validation:Optional
	Index *float64 `json:"index,omitempty" tf:"index,omitempty"`

	// Listening port of the remote syslog server.
	// +kubebuilder:validation:Required
	Port *float64 `json:"port" tf:"port,omitempty"`

	// Private key of the controller that pairs with the public certificate.
	// +kubebuilder:validation:Optional
	PrivateKeyFile *string `json:"privateKeyFile,omitempty" tf:"private_key_file,omitempty"`

	// TCP or UDP (TCP by default).
	// +kubebuilder:validation:Optional
	Protocol *string `json:"protocol,omitempty" tf:"protocol,omitempty"`

	// Public certificate of the controller signed by the same CA.
	// +kubebuilder:validation:Optional
	PublicCertificateFile *string `json:"publicCertificateFile,omitempty" tf:"public_certificate_file,omitempty"`

	// FQDN or IP address of the remote syslog server.
	// +kubebuilder:validation:Required
	Server *string `json:"server" tf:"server,omitempty"`

	// Useful when forwarding to 3rd party servers like Datadog or Sumo
	// +kubebuilder:validation:Optional
	Template *string `json:"template,omitempty" tf:"template,omitempty"`
}

// SyslogSpec defines the desired state of Syslog
type SyslogSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     SyslogParameters `json:"forProvider"`
}

// SyslogStatus defines the observed state of Syslog.
type SyslogStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        SyslogObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true

// Syslog is the Schema for the Syslogs API. <no value>
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,aviatrix}
type Syslog struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              SyslogSpec   `json:"spec"`
	Status            SyslogStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// SyslogList contains a list of Syslogs
type SyslogList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Syslog `json:"items"`
}

// Repository type metadata.
var (
	Syslog_Kind             = "Syslog"
	Syslog_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Syslog_Kind}.String()
	Syslog_KindAPIVersion   = Syslog_Kind + "." + CRDGroupVersion.String()
	Syslog_GroupVersionKind = CRDGroupVersion.WithKind(Syslog_Kind)
)

func init() {
	SchemeBuilder.Register(&Syslog{}, &SyslogList{})
}
