//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2022 Upbound Inc.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Csp) DeepCopyInto(out *Csp) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Csp.
func (in *Csp) DeepCopy() *Csp {
	if in == nil {
		return nil
	}
	out := new(Csp)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Csp) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CspList) DeepCopyInto(out *CspList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Csp, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CspList.
func (in *CspList) DeepCopy() *CspList {
	if in == nil {
		return nil
	}
	out := new(CspList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CspList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CspObservation) DeepCopyInto(out *CspObservation) {
	*out = *in
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.State != nil {
		in, out := &in.State, &out.State
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CspObservation.
func (in *CspObservation) DeepCopy() *CspObservation {
	if in == nil {
		return nil
	}
	out := new(CspObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CspParameters) DeepCopyInto(out *CspParameters) {
	*out = *in
	if in.AccountName != nil {
		in, out := &in.AccountName, &out.AccountName
		*out = new(string)
		**out = **in
	}
	if in.ApprovedLearnedCidrs != nil {
		in, out := &in.ApprovedLearnedCidrs, &out.ApprovedLearnedCidrs
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.BGPHoldTime != nil {
		in, out := &in.BGPHoldTime, &out.BGPHoldTime
		*out = new(float64)
		**out = **in
	}
	if in.BGPPollingTime != nil {
		in, out := &in.BGPPollingTime, &out.BGPPollingTime
		*out = new(float64)
		**out = **in
	}
	if in.ComputeNodeUUID != nil {
		in, out := &in.ComputeNodeUUID, &out.ComputeNodeUUID
		*out = new(string)
		**out = **in
	}
	if in.DNSServerIP != nil {
		in, out := &in.DNSServerIP, &out.DNSServerIP
		*out = new(string)
		**out = **in
	}
	if in.EnableEdgeActiveStandby != nil {
		in, out := &in.EnableEdgeActiveStandby, &out.EnableEdgeActiveStandby
		*out = new(bool)
		**out = **in
	}
	if in.EnableEdgeActiveStandbyPreemptive != nil {
		in, out := &in.EnableEdgeActiveStandbyPreemptive, &out.EnableEdgeActiveStandbyPreemptive
		*out = new(bool)
		**out = **in
	}
	if in.EnableEdgeTransitiveRouting != nil {
		in, out := &in.EnableEdgeTransitiveRouting, &out.EnableEdgeTransitiveRouting
		*out = new(bool)
		**out = **in
	}
	if in.EnableJumboFrame != nil {
		in, out := &in.EnableJumboFrame, &out.EnableJumboFrame
		*out = new(bool)
		**out = **in
	}
	if in.EnableLearnedCidrsApproval != nil {
		in, out := &in.EnableLearnedCidrsApproval, &out.EnableLearnedCidrsApproval
		*out = new(bool)
		**out = **in
	}
	if in.EnableManagementOverPrivateNetwork != nil {
		in, out := &in.EnableManagementOverPrivateNetwork, &out.EnableManagementOverPrivateNetwork
		*out = new(bool)
		**out = **in
	}
	if in.EnablePreserveAsPath != nil {
		in, out := &in.EnablePreserveAsPath, &out.EnablePreserveAsPath
		*out = new(bool)
		**out = **in
	}
	if in.GwName != nil {
		in, out := &in.GwName, &out.GwName
		*out = new(string)
		**out = **in
	}
	if in.LanInterfaceIPPrefix != nil {
		in, out := &in.LanInterfaceIPPrefix, &out.LanInterfaceIPPrefix
		*out = new(string)
		**out = **in
	}
	if in.LanInterfaceName != nil {
		in, out := &in.LanInterfaceName, &out.LanInterfaceName
		*out = new(string)
		**out = **in
	}
	if in.Latitude != nil {
		in, out := &in.Latitude, &out.Latitude
		*out = new(string)
		**out = **in
	}
	if in.LocalAsNumber != nil {
		in, out := &in.LocalAsNumber, &out.LocalAsNumber
		*out = new(string)
		**out = **in
	}
	if in.Longitude != nil {
		in, out := &in.Longitude, &out.Longitude
		*out = new(string)
		**out = **in
	}
	if in.ManagementDefaultGatewayIP != nil {
		in, out := &in.ManagementDefaultGatewayIP, &out.ManagementDefaultGatewayIP
		*out = new(string)
		**out = **in
	}
	if in.ManagementEgressIPPrefix != nil {
		in, out := &in.ManagementEgressIPPrefix, &out.ManagementEgressIPPrefix
		*out = new(string)
		**out = **in
	}
	if in.ManagementInterfaceConfig != nil {
		in, out := &in.ManagementInterfaceConfig, &out.ManagementInterfaceConfig
		*out = new(string)
		**out = **in
	}
	if in.ManagementInterfaceIPPrefix != nil {
		in, out := &in.ManagementInterfaceIPPrefix, &out.ManagementInterfaceIPPrefix
		*out = new(string)
		**out = **in
	}
	if in.ManagementInterfaceName != nil {
		in, out := &in.ManagementInterfaceName, &out.ManagementInterfaceName
		*out = new(string)
		**out = **in
	}
	if in.PrependAsPath != nil {
		in, out := &in.PrependAsPath, &out.PrependAsPath
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.ProjectUUID != nil {
		in, out := &in.ProjectUUID, &out.ProjectUUID
		*out = new(string)
		**out = **in
	}
	if in.RxQueueSize != nil {
		in, out := &in.RxQueueSize, &out.RxQueueSize
		*out = new(string)
		**out = **in
	}
	if in.SecondaryDNSServerIP != nil {
		in, out := &in.SecondaryDNSServerIP, &out.SecondaryDNSServerIP
		*out = new(string)
		**out = **in
	}
	if in.SiteID != nil {
		in, out := &in.SiteID, &out.SiteID
		*out = new(string)
		**out = **in
	}
	if in.SpokeBGPManualAdvertiseCidrs != nil {
		in, out := &in.SpokeBGPManualAdvertiseCidrs, &out.SpokeBGPManualAdvertiseCidrs
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.TemplateUUID != nil {
		in, out := &in.TemplateUUID, &out.TemplateUUID
		*out = new(string)
		**out = **in
	}
	if in.WanDefaultGatewayIP != nil {
		in, out := &in.WanDefaultGatewayIP, &out.WanDefaultGatewayIP
		*out = new(string)
		**out = **in
	}
	if in.WanInterfaceIPPrefix != nil {
		in, out := &in.WanInterfaceIPPrefix, &out.WanInterfaceIPPrefix
		*out = new(string)
		**out = **in
	}
	if in.WanInterfaceName != nil {
		in, out := &in.WanInterfaceName, &out.WanInterfaceName
		*out = new(string)
		**out = **in
	}
	if in.WanPublicIP != nil {
		in, out := &in.WanPublicIP, &out.WanPublicIP
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CspParameters.
func (in *CspParameters) DeepCopy() *CspParameters {
	if in == nil {
		return nil
	}
	out := new(CspParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CspSpec) DeepCopyInto(out *CspSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CspSpec.
func (in *CspSpec) DeepCopy() *CspSpec {
	if in == nil {
		return nil
	}
	out := new(CspSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CspStatus) DeepCopyInto(out *CspStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CspStatus.
func (in *CspStatus) DeepCopy() *CspStatus {
	if in == nil {
		return nil
	}
	out := new(CspStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Spoke) DeepCopyInto(out *Spoke) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Spoke.
func (in *Spoke) DeepCopy() *Spoke {
	if in == nil {
		return nil
	}
	out := new(Spoke)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Spoke) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SpokeExternalDeviceConn) DeepCopyInto(out *SpokeExternalDeviceConn) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SpokeExternalDeviceConn.
func (in *SpokeExternalDeviceConn) DeepCopy() *SpokeExternalDeviceConn {
	if in == nil {
		return nil
	}
	out := new(SpokeExternalDeviceConn)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SpokeExternalDeviceConn) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SpokeExternalDeviceConnList) DeepCopyInto(out *SpokeExternalDeviceConnList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SpokeExternalDeviceConn, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SpokeExternalDeviceConnList.
func (in *SpokeExternalDeviceConnList) DeepCopy() *SpokeExternalDeviceConnList {
	if in == nil {
		return nil
	}
	out := new(SpokeExternalDeviceConnList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SpokeExternalDeviceConnList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SpokeExternalDeviceConnObservation) DeepCopyInto(out *SpokeExternalDeviceConnObservation) {
	*out = *in
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SpokeExternalDeviceConnObservation.
func (in *SpokeExternalDeviceConnObservation) DeepCopy() *SpokeExternalDeviceConnObservation {
	if in == nil {
		return nil
	}
	out := new(SpokeExternalDeviceConnObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SpokeExternalDeviceConnParameters) DeepCopyInto(out *SpokeExternalDeviceConnParameters) {
	*out = *in
	if in.BGPLocalAsNum != nil {
		in, out := &in.BGPLocalAsNum, &out.BGPLocalAsNum
		*out = new(string)
		**out = **in
	}
	if in.BGPRemoteAsNum != nil {
		in, out := &in.BGPRemoteAsNum, &out.BGPRemoteAsNum
		*out = new(string)
		**out = **in
	}
	if in.ConnectionName != nil {
		in, out := &in.ConnectionName, &out.ConnectionName
		*out = new(string)
		**out = **in
	}
	if in.ConnectionType != nil {
		in, out := &in.ConnectionType, &out.ConnectionType
		*out = new(string)
		**out = **in
	}
	if in.GwName != nil {
		in, out := &in.GwName, &out.GwName
		*out = new(string)
		**out = **in
	}
	if in.LocalLanIP != nil {
		in, out := &in.LocalLanIP, &out.LocalLanIP
		*out = new(string)
		**out = **in
	}
	if in.NumberOfRetries != nil {
		in, out := &in.NumberOfRetries, &out.NumberOfRetries
		*out = new(float64)
		**out = **in
	}
	if in.RemoteLanIP != nil {
		in, out := &in.RemoteLanIP, &out.RemoteLanIP
		*out = new(string)
		**out = **in
	}
	if in.RetryInterval != nil {
		in, out := &in.RetryInterval, &out.RetryInterval
		*out = new(float64)
		**out = **in
	}
	if in.SiteID != nil {
		in, out := &in.SiteID, &out.SiteID
		*out = new(string)
		**out = **in
	}
	if in.TunnelProtocol != nil {
		in, out := &in.TunnelProtocol, &out.TunnelProtocol
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SpokeExternalDeviceConnParameters.
func (in *SpokeExternalDeviceConnParameters) DeepCopy() *SpokeExternalDeviceConnParameters {
	if in == nil {
		return nil
	}
	out := new(SpokeExternalDeviceConnParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SpokeExternalDeviceConnSpec) DeepCopyInto(out *SpokeExternalDeviceConnSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SpokeExternalDeviceConnSpec.
func (in *SpokeExternalDeviceConnSpec) DeepCopy() *SpokeExternalDeviceConnSpec {
	if in == nil {
		return nil
	}
	out := new(SpokeExternalDeviceConnSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SpokeExternalDeviceConnStatus) DeepCopyInto(out *SpokeExternalDeviceConnStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SpokeExternalDeviceConnStatus.
func (in *SpokeExternalDeviceConnStatus) DeepCopy() *SpokeExternalDeviceConnStatus {
	if in == nil {
		return nil
	}
	out := new(SpokeExternalDeviceConnStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SpokeList) DeepCopyInto(out *SpokeList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Spoke, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SpokeList.
func (in *SpokeList) DeepCopy() *SpokeList {
	if in == nil {
		return nil
	}
	out := new(SpokeList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SpokeList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SpokeObservation) DeepCopyInto(out *SpokeObservation) {
	*out = *in
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.State != nil {
		in, out := &in.State, &out.State
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SpokeObservation.
func (in *SpokeObservation) DeepCopy() *SpokeObservation {
	if in == nil {
		return nil
	}
	out := new(SpokeObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SpokeParameters) DeepCopyInto(out *SpokeParameters) {
	*out = *in
	if in.ApprovedLearnedCidrs != nil {
		in, out := &in.ApprovedLearnedCidrs, &out.ApprovedLearnedCidrs
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.BGPHoldTime != nil {
		in, out := &in.BGPHoldTime, &out.BGPHoldTime
		*out = new(float64)
		**out = **in
	}
	if in.BGPPollingTime != nil {
		in, out := &in.BGPPollingTime, &out.BGPPollingTime
		*out = new(float64)
		**out = **in
	}
	if in.DNSServerIP != nil {
		in, out := &in.DNSServerIP, &out.DNSServerIP
		*out = new(string)
		**out = **in
	}
	if in.EnableEdgeActiveStandby != nil {
		in, out := &in.EnableEdgeActiveStandby, &out.EnableEdgeActiveStandby
		*out = new(bool)
		**out = **in
	}
	if in.EnableEdgeActiveStandbyPreemptive != nil {
		in, out := &in.EnableEdgeActiveStandbyPreemptive, &out.EnableEdgeActiveStandbyPreemptive
		*out = new(bool)
		**out = **in
	}
	if in.EnableEdgeTransitiveRouting != nil {
		in, out := &in.EnableEdgeTransitiveRouting, &out.EnableEdgeTransitiveRouting
		*out = new(bool)
		**out = **in
	}
	if in.EnableJumboFrame != nil {
		in, out := &in.EnableJumboFrame, &out.EnableJumboFrame
		*out = new(bool)
		**out = **in
	}
	if in.EnableLearnedCidrsApproval != nil {
		in, out := &in.EnableLearnedCidrsApproval, &out.EnableLearnedCidrsApproval
		*out = new(bool)
		**out = **in
	}
	if in.EnableManagementOverPrivateNetwork != nil {
		in, out := &in.EnableManagementOverPrivateNetwork, &out.EnableManagementOverPrivateNetwork
		*out = new(bool)
		**out = **in
	}
	if in.EnablePreserveAsPath != nil {
		in, out := &in.EnablePreserveAsPath, &out.EnablePreserveAsPath
		*out = new(bool)
		**out = **in
	}
	if in.GwName != nil {
		in, out := &in.GwName, &out.GwName
		*out = new(string)
		**out = **in
	}
	if in.LanInterfaceIPPrefix != nil {
		in, out := &in.LanInterfaceIPPrefix, &out.LanInterfaceIPPrefix
		*out = new(string)
		**out = **in
	}
	if in.Latitude != nil {
		in, out := &in.Latitude, &out.Latitude
		*out = new(string)
		**out = **in
	}
	if in.LocalAsNumber != nil {
		in, out := &in.LocalAsNumber, &out.LocalAsNumber
		*out = new(string)
		**out = **in
	}
	if in.Longitude != nil {
		in, out := &in.Longitude, &out.Longitude
		*out = new(string)
		**out = **in
	}
	if in.ManagementDefaultGatewayIP != nil {
		in, out := &in.ManagementDefaultGatewayIP, &out.ManagementDefaultGatewayIP
		*out = new(string)
		**out = **in
	}
	if in.ManagementEgressIPPrefix != nil {
		in, out := &in.ManagementEgressIPPrefix, &out.ManagementEgressIPPrefix
		*out = new(string)
		**out = **in
	}
	if in.ManagementInterfaceConfig != nil {
		in, out := &in.ManagementInterfaceConfig, &out.ManagementInterfaceConfig
		*out = new(string)
		**out = **in
	}
	if in.ManagementInterfaceIPPrefix != nil {
		in, out := &in.ManagementInterfaceIPPrefix, &out.ManagementInterfaceIPPrefix
		*out = new(string)
		**out = **in
	}
	if in.PrependAsPath != nil {
		in, out := &in.PrependAsPath, &out.PrependAsPath
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.RxQueueSize != nil {
		in, out := &in.RxQueueSize, &out.RxQueueSize
		*out = new(string)
		**out = **in
	}
	if in.SecondaryDNSServerIP != nil {
		in, out := &in.SecondaryDNSServerIP, &out.SecondaryDNSServerIP
		*out = new(string)
		**out = **in
	}
	if in.SiteID != nil {
		in, out := &in.SiteID, &out.SiteID
		*out = new(string)
		**out = **in
	}
	if in.SpokeBGPManualAdvertiseCidrs != nil {
		in, out := &in.SpokeBGPManualAdvertiseCidrs, &out.SpokeBGPManualAdvertiseCidrs
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.WanDefaultGatewayIP != nil {
		in, out := &in.WanDefaultGatewayIP, &out.WanDefaultGatewayIP
		*out = new(string)
		**out = **in
	}
	if in.WanInterfaceIPPrefix != nil {
		in, out := &in.WanInterfaceIPPrefix, &out.WanInterfaceIPPrefix
		*out = new(string)
		**out = **in
	}
	if in.WanPublicIP != nil {
		in, out := &in.WanPublicIP, &out.WanPublicIP
		*out = new(string)
		**out = **in
	}
	if in.ZtpFileDownloadPath != nil {
		in, out := &in.ZtpFileDownloadPath, &out.ZtpFileDownloadPath
		*out = new(string)
		**out = **in
	}
	if in.ZtpFileType != nil {
		in, out := &in.ZtpFileType, &out.ZtpFileType
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SpokeParameters.
func (in *SpokeParameters) DeepCopy() *SpokeParameters {
	if in == nil {
		return nil
	}
	out := new(SpokeParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SpokeSpec) DeepCopyInto(out *SpokeSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SpokeSpec.
func (in *SpokeSpec) DeepCopy() *SpokeSpec {
	if in == nil {
		return nil
	}
	out := new(SpokeSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SpokeStatus) DeepCopyInto(out *SpokeStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SpokeStatus.
func (in *SpokeStatus) DeepCopy() *SpokeStatus {
	if in == nil {
		return nil
	}
	out := new(SpokeStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SpokeTransitAttachment) DeepCopyInto(out *SpokeTransitAttachment) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SpokeTransitAttachment.
func (in *SpokeTransitAttachment) DeepCopy() *SpokeTransitAttachment {
	if in == nil {
		return nil
	}
	out := new(SpokeTransitAttachment)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SpokeTransitAttachment) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SpokeTransitAttachmentList) DeepCopyInto(out *SpokeTransitAttachmentList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SpokeTransitAttachment, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SpokeTransitAttachmentList.
func (in *SpokeTransitAttachmentList) DeepCopy() *SpokeTransitAttachmentList {
	if in == nil {
		return nil
	}
	out := new(SpokeTransitAttachmentList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SpokeTransitAttachmentList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SpokeTransitAttachmentObservation) DeepCopyInto(out *SpokeTransitAttachmentObservation) {
	*out = *in
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SpokeTransitAttachmentObservation.
func (in *SpokeTransitAttachmentObservation) DeepCopy() *SpokeTransitAttachmentObservation {
	if in == nil {
		return nil
	}
	out := new(SpokeTransitAttachmentObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SpokeTransitAttachmentParameters) DeepCopyInto(out *SpokeTransitAttachmentParameters) {
	*out = *in
	if in.EnableInsaneMode != nil {
		in, out := &in.EnableInsaneMode, &out.EnableInsaneMode
		*out = new(bool)
		**out = **in
	}
	if in.EnableJumboFrame != nil {
		in, out := &in.EnableJumboFrame, &out.EnableJumboFrame
		*out = new(bool)
		**out = **in
	}
	if in.EnableOverPrivateNetwork != nil {
		in, out := &in.EnableOverPrivateNetwork, &out.EnableOverPrivateNetwork
		*out = new(bool)
		**out = **in
	}
	if in.InsaneModeTunnelNumber != nil {
		in, out := &in.InsaneModeTunnelNumber, &out.InsaneModeTunnelNumber
		*out = new(float64)
		**out = **in
	}
	if in.NumberOfRetries != nil {
		in, out := &in.NumberOfRetries, &out.NumberOfRetries
		*out = new(float64)
		**out = **in
	}
	if in.RetryInterval != nil {
		in, out := &in.RetryInterval, &out.RetryInterval
		*out = new(float64)
		**out = **in
	}
	if in.SpokeGwName != nil {
		in, out := &in.SpokeGwName, &out.SpokeGwName
		*out = new(string)
		**out = **in
	}
	if in.SpokePrependAsPath != nil {
		in, out := &in.SpokePrependAsPath, &out.SpokePrependAsPath
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.TransitGwName != nil {
		in, out := &in.TransitGwName, &out.TransitGwName
		*out = new(string)
		**out = **in
	}
	if in.TransitPrependAsPath != nil {
		in, out := &in.TransitPrependAsPath, &out.TransitPrependAsPath
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SpokeTransitAttachmentParameters.
func (in *SpokeTransitAttachmentParameters) DeepCopy() *SpokeTransitAttachmentParameters {
	if in == nil {
		return nil
	}
	out := new(SpokeTransitAttachmentParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SpokeTransitAttachmentSpec) DeepCopyInto(out *SpokeTransitAttachmentSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SpokeTransitAttachmentSpec.
func (in *SpokeTransitAttachmentSpec) DeepCopy() *SpokeTransitAttachmentSpec {
	if in == nil {
		return nil
	}
	out := new(SpokeTransitAttachmentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SpokeTransitAttachmentStatus) DeepCopyInto(out *SpokeTransitAttachmentStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SpokeTransitAttachmentStatus.
func (in *SpokeTransitAttachmentStatus) DeepCopy() *SpokeTransitAttachmentStatus {
	if in == nil {
		return nil
	}
	out := new(SpokeTransitAttachmentStatus)
	in.DeepCopyInto(out)
	return out
}
