/*
Copyright 2022 Upbound Inc.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type SpokeExternalDeviceConnObservation struct {
	ID *string `json:"id,omitempty" tf:"id,omitempty"`
}

type SpokeExternalDeviceConnParameters struct {

	// BGP local AS number.
	// +kubebuilder:validation:Required
	BGPLocalAsNum *string `json:"bgpLocalAsNum" tf:"bgp_local_as_num,omitempty"`

	// BGP remote AS number.
	// +kubebuilder:validation:Required
	BGPRemoteAsNum *string `json:"bgpRemoteAsNum" tf:"bgp_remote_as_num,omitempty"`

	// The name of the spoke external device connection which is going to be created.
	// +kubebuilder:validation:Required
	ConnectionName *string `json:"connectionName" tf:"connection_name,omitempty"`

	// Connection type. Valid values: 'bgp'. Default value: 'bgp'.
	// +kubebuilder:validation:Optional
	ConnectionType *string `json:"connectionType,omitempty" tf:"connection_type,omitempty"`

	// Name of the BGP Spoke Gateway.
	// +kubebuilder:validation:Required
	GwName *string `json:"gwName" tf:"gw_name,omitempty"`

	// Local LAN IP.
	// +kubebuilder:validation:Required
	LocalLanIP *string `json:"localLanIp" tf:"local_lan_ip,omitempty"`

	// Number of retries.
	// +kubebuilder:validation:Optional
	NumberOfRetries *float64 `json:"numberOfRetries,omitempty" tf:"number_of_retries,omitempty"`

	// Remote LAN IP.
	// +kubebuilder:validation:Required
	RemoteLanIP *string `json:"remoteLanIp" tf:"remote_lan_ip,omitempty"`

	// Retry interval in seconds.
	// +kubebuilder:validation:Optional
	RetryInterval *float64 `json:"retryInterval,omitempty" tf:"retry_interval,omitempty"`

	// ID of the VPC where the BGP Spoke Gateway is located.
	// +kubebuilder:validation:Required
	SiteID *string `json:"siteId" tf:"site_id,omitempty"`

	// Tunnel Protocol. Valid value: 'LAN'. Default value: 'LAN'. Case insensitive.
	// +kubebuilder:validation:Optional
	TunnelProtocol *string `json:"tunnelProtocol,omitempty" tf:"tunnel_protocol,omitempty"`
}

// SpokeExternalDeviceConnSpec defines the desired state of SpokeExternalDeviceConn
type SpokeExternalDeviceConnSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     SpokeExternalDeviceConnParameters `json:"forProvider"`
}

// SpokeExternalDeviceConnStatus defines the observed state of SpokeExternalDeviceConn.
type SpokeExternalDeviceConnStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        SpokeExternalDeviceConnObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true

// SpokeExternalDeviceConn is the Schema for the SpokeExternalDeviceConns API. <no value>
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,aviatrix}
type SpokeExternalDeviceConn struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              SpokeExternalDeviceConnSpec   `json:"spec"`
	Status            SpokeExternalDeviceConnStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// SpokeExternalDeviceConnList contains a list of SpokeExternalDeviceConns
type SpokeExternalDeviceConnList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []SpokeExternalDeviceConn `json:"items"`
}

// Repository type metadata.
var (
	SpokeExternalDeviceConn_Kind             = "SpokeExternalDeviceConn"
	SpokeExternalDeviceConn_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: SpokeExternalDeviceConn_Kind}.String()
	SpokeExternalDeviceConn_KindAPIVersion   = SpokeExternalDeviceConn_Kind + "." + CRDGroupVersion.String()
	SpokeExternalDeviceConn_GroupVersionKind = CRDGroupVersion.WithKind(SpokeExternalDeviceConn_Kind)
)

func init() {
	SchemeBuilder.Register(&SpokeExternalDeviceConn{}, &SpokeExternalDeviceConnList{})
}
