/*
Copyright 2022 Upbound Inc.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type ManagementAccessObservation struct {
	ID *string `json:"id,omitempty" tf:"id,omitempty"`
}

type ManagementAccessParameters struct {

	// Name of the resource to be enabled firewall management access.
	// +kubebuilder:validation:Required
	ManagementAccessResourceName *string `json:"managementAccessResourceName" tf:"management_access_resource_name,omitempty"`

	// Name of the transit firenet gateway.
	// +kubebuilder:validation:Required
	TransitFirenetGatewayName *string `json:"transitFirenetGatewayName" tf:"transit_firenet_gateway_name,omitempty"`
}

// ManagementAccessSpec defines the desired state of ManagementAccess
type ManagementAccessSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     ManagementAccessParameters `json:"forProvider"`
}

// ManagementAccessStatus defines the observed state of ManagementAccess.
type ManagementAccessStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        ManagementAccessObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true

// ManagementAccess is the Schema for the ManagementAccesss API. <no value>
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,aviatrix}
type ManagementAccess struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              ManagementAccessSpec   `json:"spec"`
	Status            ManagementAccessStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// ManagementAccessList contains a list of ManagementAccesss
type ManagementAccessList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []ManagementAccess `json:"items"`
}

// Repository type metadata.
var (
	ManagementAccess_Kind             = "ManagementAccess"
	ManagementAccess_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: ManagementAccess_Kind}.String()
	ManagementAccess_KindAPIVersion   = ManagementAccess_Kind + "." + CRDGroupVersion.String()
	ManagementAccess_GroupVersionKind = CRDGroupVersion.WithKind(ManagementAccess_Kind)
)

func init() {
	SchemeBuilder.Register(&ManagementAccess{}, &ManagementAccessList{})
}
