/*
Copyright 2022 Upbound Inc.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type SpokeNativePeeringObservation struct {
	ID *string `json:"id,omitempty" tf:"id,omitempty"`
}

type SpokeNativePeeringParameters struct {

	// An Aviatrix account that corresponds to a subscription in Azure.
	// +kubebuilder:validation:Required
	SpokeAccountName *string `json:"spokeAccountName" tf:"spoke_account_name,omitempty"`

	// Spoke VNet region.
	// +kubebuilder:validation:Required
	SpokeRegion *string `json:"spokeRegion" tf:"spoke_region,omitempty"`

	// Combination of the Spoke VNet name and resource group.
	// +kubebuilder:validation:Required
	SpokeVPCID *string `json:"spokeVpcId" tf:"spoke_vpc_id,omitempty"`

	// Name of an azure transit gateway with transit firenet enabled.
	// +kubebuilder:validation:Required
	TransitGatewayName *string `json:"transitGatewayName" tf:"transit_gateway_name,omitempty"`
}

// SpokeNativePeeringSpec defines the desired state of SpokeNativePeering
type SpokeNativePeeringSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     SpokeNativePeeringParameters `json:"forProvider"`
}

// SpokeNativePeeringStatus defines the observed state of SpokeNativePeering.
type SpokeNativePeeringStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        SpokeNativePeeringObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true

// SpokeNativePeering is the Schema for the SpokeNativePeerings API. <no value>
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,aviatrix}
type SpokeNativePeering struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              SpokeNativePeeringSpec   `json:"spec"`
	Status            SpokeNativePeeringStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// SpokeNativePeeringList contains a list of SpokeNativePeerings
type SpokeNativePeeringList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []SpokeNativePeering `json:"items"`
}

// Repository type metadata.
var (
	SpokeNativePeering_Kind             = "SpokeNativePeering"
	SpokeNativePeering_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: SpokeNativePeering_Kind}.String()
	SpokeNativePeering_KindAPIVersion   = SpokeNativePeering_Kind + "." + CRDGroupVersion.String()
	SpokeNativePeering_GroupVersionKind = CRDGroupVersion.WithKind(SpokeNativePeering_Kind)
)

func init() {
	SchemeBuilder.Register(&SpokeNativePeering{}, &SpokeNativePeeringList{})
}
