/*
Copyright 2022 Upbound Inc.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type VngConnObservation struct {

	// VNG attached or not
	Attached *bool `json:"attached,omitempty" tf:"attached,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// VPC ID
	VPCID *string `json:"vpcId,omitempty" tf:"vpc_id,omitempty"`

	// VNG name
	VngName *string `json:"vngName,omitempty" tf:"vng_name,omitempty"`
}

type VngConnParameters struct {

	// Primary gateway name
	// +kubebuilder:validation:Required
	PrimaryGatewayName *string `json:"primaryGatewayName" tf:"primary_gateway_name,omitempty"`
}

// VngConnSpec defines the desired state of VngConn
type VngConnSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     VngConnParameters `json:"forProvider"`
}

// VngConnStatus defines the observed state of VngConn.
type VngConnStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        VngConnObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true

// VngConn is the Schema for the VngConns API. <no value>
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,aviatrix}
type VngConn struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              VngConnSpec   `json:"spec"`
	Status            VngConnStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// VngConnList contains a list of VngConns
type VngConnList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []VngConn `json:"items"`
}

// Repository type metadata.
var (
	VngConn_Kind             = "VngConn"
	VngConn_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: VngConn_Kind}.String()
	VngConn_KindAPIVersion   = VngConn_Kind + "." + CRDGroupVersion.String()
	VngConn_GroupVersionKind = CRDGroupVersion.WithKind(VngConn_Kind)
)

func init() {
	SchemeBuilder.Register(&VngConn{}, &VngConnList{})
}
