apiVersion: spoke.aviatrix.upbound.io/v1alpha1
kind: Gateway
metadata:
  annotations:
    meta.upbound.io/example-id: spoke/v1alpha1/gateway
  labels:
    testing.upbound.io/example-name: test_spoke_gateway_aws
  name: test-spoke-gateway-aws
spec:
  forProvider:
    accountName: aviatrix
    cloudType: 4
    gwSize: n1-highcpu-16
    manageHaGateway: false
    singleIpSnat: false
    subnet: 10.10.1.0/24
    vpcId: gcloud-vpc-spoke~-~mconnors-01
    vpcReg: us-west-1

---

apiVersion: aviatrix.aviatrix.upbound.io/v1alpha1
kind: VPC
metadata:
  name: gcloud-vpc-spoke
spec:
  forProvider:
    accountName: aviatrix
    aviatrixFirenetVpc: false
    aviatrixTransitVpc: false
    cloudType: 4
    subnets:
    - cidr: 10.10.1.0/24
      name: subnet-2
      region: us-west1
  providerConfigRef:
    name: default

