
apiVersion: aviatrix.aviatrix.upbound.io/v1alpha1
kind: VPC
metadata:
  name: gcloud-vpc-spoke
spec:
  forProvider:
    accountName: aviatrix
    aviatrixFirenetVpc: false
    aviatrixTransitVpc: false
    cloudType: 4
    subnets:
    - cidr: 10.10.1.0/24
      name: subnet-2
      region: us-west1
  providerConfigRef:
    name: default

