//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2022 Upbound Inc.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModeLB) DeepCopyInto(out *ModeLB) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModeLB.
func (in *ModeLB) DeepCopy() *ModeLB {
	if in == nil {
		return nil
	}
	out := new(ModeLB)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ModeLB) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModeLBList) DeepCopyInto(out *ModeLBList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ModeLB, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModeLBList.
func (in *ModeLBList) DeepCopy() *ModeLBList {
	if in == nil {
		return nil
	}
	out := new(ModeLBList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ModeLBList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModeLBObservation) DeepCopyInto(out *ModeLBObservation) {
	*out = *in
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModeLBObservation.
func (in *ModeLBObservation) DeepCopy() *ModeLBObservation {
	if in == nil {
		return nil
	}
	out := new(ModeLBObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModeLBParameters) DeepCopyInto(out *ModeLBParameters) {
	*out = *in
	if in.AccountName != nil {
		in, out := &in.AccountName, &out.AccountName
		*out = new(string)
		**out = **in
	}
	if in.LBType != nil {
		in, out := &in.LBType, &out.LBType
		*out = new(string)
		**out = **in
	}
	if in.MulticloudAccessVPCID != nil {
		in, out := &in.MulticloudAccessVPCID, &out.MulticloudAccessVPCID
		*out = new(string)
		**out = **in
	}
	if in.Proxies != nil {
		in, out := &in.Proxies, &out.Proxies
		*out = make([]ProxiesParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Region != nil {
		in, out := &in.Region, &out.Region
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModeLBParameters.
func (in *ModeLBParameters) DeepCopy() *ModeLBParameters {
	if in == nil {
		return nil
	}
	out := new(ModeLBParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModeLBSpec) DeepCopyInto(out *ModeLBSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModeLBSpec.
func (in *ModeLBSpec) DeepCopy() *ModeLBSpec {
	if in == nil {
		return nil
	}
	out := new(ModeLBSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModeLBStatus) DeepCopyInto(out *ModeLBStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModeLBStatus.
func (in *ModeLBStatus) DeepCopy() *ModeLBStatus {
	if in == nil {
		return nil
	}
	out := new(ModeLBStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModeMulticloudEndpoint) DeepCopyInto(out *ModeMulticloudEndpoint) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModeMulticloudEndpoint.
func (in *ModeMulticloudEndpoint) DeepCopy() *ModeMulticloudEndpoint {
	if in == nil {
		return nil
	}
	out := new(ModeMulticloudEndpoint)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ModeMulticloudEndpoint) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModeMulticloudEndpointList) DeepCopyInto(out *ModeMulticloudEndpointList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ModeMulticloudEndpoint, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModeMulticloudEndpointList.
func (in *ModeMulticloudEndpointList) DeepCopy() *ModeMulticloudEndpointList {
	if in == nil {
		return nil
	}
	out := new(ModeMulticloudEndpointList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ModeMulticloudEndpointList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModeMulticloudEndpointObservation) DeepCopyInto(out *ModeMulticloudEndpointObservation) {
	*out = *in
	if in.DNSEntry != nil {
		in, out := &in.DNSEntry, &out.DNSEntry
		*out = new(string)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModeMulticloudEndpointObservation.
func (in *ModeMulticloudEndpointObservation) DeepCopy() *ModeMulticloudEndpointObservation {
	if in == nil {
		return nil
	}
	out := new(ModeMulticloudEndpointObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModeMulticloudEndpointParameters) DeepCopyInto(out *ModeMulticloudEndpointParameters) {
	*out = *in
	if in.AccountName != nil {
		in, out := &in.AccountName, &out.AccountName
		*out = new(string)
		**out = **in
	}
	if in.ControllerLBVPCID != nil {
		in, out := &in.ControllerLBVPCID, &out.ControllerLBVPCID
		*out = new(string)
		**out = **in
	}
	if in.Region != nil {
		in, out := &in.Region, &out.Region
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModeMulticloudEndpointParameters.
func (in *ModeMulticloudEndpointParameters) DeepCopy() *ModeMulticloudEndpointParameters {
	if in == nil {
		return nil
	}
	out := new(ModeMulticloudEndpointParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModeMulticloudEndpointSpec) DeepCopyInto(out *ModeMulticloudEndpointSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModeMulticloudEndpointSpec.
func (in *ModeMulticloudEndpointSpec) DeepCopy() *ModeMulticloudEndpointSpec {
	if in == nil {
		return nil
	}
	out := new(ModeMulticloudEndpointSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModeMulticloudEndpointStatus) DeepCopyInto(out *ModeMulticloudEndpointStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModeMulticloudEndpointStatus.
func (in *ModeMulticloudEndpointStatus) DeepCopy() *ModeMulticloudEndpointStatus {
	if in == nil {
		return nil
	}
	out := new(ModeMulticloudEndpointStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProxiesObservation) DeepCopyInto(out *ProxiesObservation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProxiesObservation.
func (in *ProxiesObservation) DeepCopy() *ProxiesObservation {
	if in == nil {
		return nil
	}
	out := new(ProxiesObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProxiesParameters) DeepCopyInto(out *ProxiesParameters) {
	*out = *in
	if in.InstanceID != nil {
		in, out := &in.InstanceID, &out.InstanceID
		*out = new(string)
		**out = **in
	}
	if in.VPCID != nil {
		in, out := &in.VPCID, &out.VPCID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProxiesParameters.
func (in *ProxiesParameters) DeepCopy() *ProxiesParameters {
	if in == nil {
		return nil
	}
	out := new(ProxiesParameters)
	in.DeepCopyInto(out)
	return out
}
