/*
Copyright 2022 Upbound Inc.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	"github.com/pkg/errors"

	"github.com/upbound/upjet/pkg/resource"
	"github.com/upbound/upjet/pkg/resource/json"
)

// GetTerraformResourceType returns Terraform resource type for this GuardDuty
func (mg *GuardDuty) GetTerraformResourceType() string {
	return "aviatrix_aws_guard_duty"
}

// GetConnectionDetailsMapping for this GuardDuty
func (tr *GuardDuty) GetConnectionDetailsMapping() map[string]string {
	return nil
}

// GetObservation of this GuardDuty
func (tr *GuardDuty) GetObservation() (map[string]any, error) {
	o, err := json.TFParser.Marshal(tr.Status.AtProvider)
	if err != nil {
		return nil, err
	}
	base := map[string]any{}
	return base, json.TFParser.Unmarshal(o, &base)
}

// SetObservation for this GuardDuty
func (tr *GuardDuty) SetObservation(obs map[string]any) error {
	p, err := json.TFParser.Marshal(obs)
	if err != nil {
		return err
	}
	return json.TFParser.Unmarshal(p, &tr.Status.AtProvider)
}

// GetID returns ID of underlying Terraform resource of this GuardDuty
func (tr *GuardDuty) GetID() string {
	if tr.Status.AtProvider.ID == nil {
		return ""
	}
	return *tr.Status.AtProvider.ID
}

// GetParameters of this GuardDuty
func (tr *GuardDuty) GetParameters() (map[string]any, error) {
	p, err := json.TFParser.Marshal(tr.Spec.ForProvider)
	if err != nil {
		return nil, err
	}
	base := map[string]any{}
	return base, json.TFParser.Unmarshal(p, &base)
}

// SetParameters for this GuardDuty
func (tr *GuardDuty) SetParameters(params map[string]any) error {
	p, err := json.TFParser.Marshal(params)
	if err != nil {
		return err
	}
	return json.TFParser.Unmarshal(p, &tr.Spec.ForProvider)
}

// LateInitialize this GuardDuty using its observed tfState.
// returns True if there are any spec changes for the resource.
func (tr *GuardDuty) LateInitialize(attrs []byte) (bool, error) {
	params := &GuardDutyParameters{}
	if err := json.TFParser.Unmarshal(attrs, params); err != nil {
		return false, errors.Wrap(err, "failed to unmarshal Terraform state parameters for late-initialization")
	}
	opts := []resource.GenericLateInitializerOption{resource.WithZeroValueJSONOmitEmptyFilter(resource.CNameWildcard)}

	li := resource.NewGenericLateInitializer(opts...)
	return li.LateInitialize(&tr.Spec.ForProvider, params)
}

// GetTerraformSchemaVersion returns the associated Terraform schema version
func (tr *GuardDuty) GetTerraformSchemaVersion() int {
	return 0
}

// GetTerraformResourceType returns Terraform resource type for this Peer
func (mg *Peer) GetTerraformResourceType() string {
	return "aviatrix_aws_peer"
}

// GetConnectionDetailsMapping for this Peer
func (tr *Peer) GetConnectionDetailsMapping() map[string]string {
	return nil
}

// GetObservation of this Peer
func (tr *Peer) GetObservation() (map[string]any, error) {
	o, err := json.TFParser.Marshal(tr.Status.AtProvider)
	if err != nil {
		return nil, err
	}
	base := map[string]any{}
	return base, json.TFParser.Unmarshal(o, &base)
}

// SetObservation for this Peer
func (tr *Peer) SetObservation(obs map[string]any) error {
	p, err := json.TFParser.Marshal(obs)
	if err != nil {
		return err
	}
	return json.TFParser.Unmarshal(p, &tr.Status.AtProvider)
}

// GetID returns ID of underlying Terraform resource of this Peer
func (tr *Peer) GetID() string {
	if tr.Status.AtProvider.ID == nil {
		return ""
	}
	return *tr.Status.AtProvider.ID
}

// GetParameters of this Peer
func (tr *Peer) GetParameters() (map[string]any, error) {
	p, err := json.TFParser.Marshal(tr.Spec.ForProvider)
	if err != nil {
		return nil, err
	}
	base := map[string]any{}
	return base, json.TFParser.Unmarshal(p, &base)
}

// SetParameters for this Peer
func (tr *Peer) SetParameters(params map[string]any) error {
	p, err := json.TFParser.Marshal(params)
	if err != nil {
		return err
	}
	return json.TFParser.Unmarshal(p, &tr.Spec.ForProvider)
}

// LateInitialize this Peer using its observed tfState.
// returns True if there are any spec changes for the resource.
func (tr *Peer) LateInitialize(attrs []byte) (bool, error) {
	params := &PeerParameters{}
	if err := json.TFParser.Unmarshal(attrs, params); err != nil {
		return false, errors.Wrap(err, "failed to unmarshal Terraform state parameters for late-initialization")
	}
	opts := []resource.GenericLateInitializerOption{resource.WithZeroValueJSONOmitEmptyFilter(resource.CNameWildcard)}

	li := resource.NewGenericLateInitializer(opts...)
	return li.LateInitialize(&tr.Spec.ForProvider, params)
}

// GetTerraformSchemaVersion returns the associated Terraform schema version
func (tr *Peer) GetTerraformSchemaVersion() int {
	return 0
}

// GetTerraformResourceType returns Terraform resource type for this Tgw
func (mg *Tgw) GetTerraformResourceType() string {
	return "aviatrix_aws_tgw"
}

// GetConnectionDetailsMapping for this Tgw
func (tr *Tgw) GetConnectionDetailsMapping() map[string]string {
	return nil
}

// GetObservation of this Tgw
func (tr *Tgw) GetObservation() (map[string]any, error) {
	o, err := json.TFParser.Marshal(tr.Status.AtProvider)
	if err != nil {
		return nil, err
	}
	base := map[string]any{}
	return base, json.TFParser.Unmarshal(o, &base)
}

// SetObservation for this Tgw
func (tr *Tgw) SetObservation(obs map[string]any) error {
	p, err := json.TFParser.Marshal(obs)
	if err != nil {
		return err
	}
	return json.TFParser.Unmarshal(p, &tr.Status.AtProvider)
}

// GetID returns ID of underlying Terraform resource of this Tgw
func (tr *Tgw) GetID() string {
	if tr.Status.AtProvider.ID == nil {
		return ""
	}
	return *tr.Status.AtProvider.ID
}

// GetParameters of this Tgw
func (tr *Tgw) GetParameters() (map[string]any, error) {
	p, err := json.TFParser.Marshal(tr.Spec.ForProvider)
	if err != nil {
		return nil, err
	}
	base := map[string]any{}
	return base, json.TFParser.Unmarshal(p, &base)
}

// SetParameters for this Tgw
func (tr *Tgw) SetParameters(params map[string]any) error {
	p, err := json.TFParser.Marshal(params)
	if err != nil {
		return err
	}
	return json.TFParser.Unmarshal(p, &tr.Spec.ForProvider)
}

// LateInitialize this Tgw using its observed tfState.
// returns True if there are any spec changes for the resource.
func (tr *Tgw) LateInitialize(attrs []byte) (bool, error) {
	params := &TgwParameters{}
	if err := json.TFParser.Unmarshal(attrs, params); err != nil {
		return false, errors.Wrap(err, "failed to unmarshal Terraform state parameters for late-initialization")
	}
	opts := []resource.GenericLateInitializerOption{resource.WithZeroValueJSONOmitEmptyFilter(resource.CNameWildcard)}

	li := resource.NewGenericLateInitializer(opts...)
	return li.LateInitialize(&tr.Spec.ForProvider, params)
}

// GetTerraformSchemaVersion returns the associated Terraform schema version
func (tr *Tgw) GetTerraformSchemaVersion() int {
	return 3
}

// GetTerraformResourceType returns Terraform resource type for this TgwConnect
func (mg *TgwConnect) GetTerraformResourceType() string {
	return "aviatrix_aws_tgw_connect"
}

// GetConnectionDetailsMapping for this TgwConnect
func (tr *TgwConnect) GetConnectionDetailsMapping() map[string]string {
	return nil
}

// GetObservation of this TgwConnect
func (tr *TgwConnect) GetObservation() (map[string]any, error) {
	o, err := json.TFParser.Marshal(tr.Status.AtProvider)
	if err != nil {
		return nil, err
	}
	base := map[string]any{}
	return base, json.TFParser.Unmarshal(o, &base)
}

// SetObservation for this TgwConnect
func (tr *TgwConnect) SetObservation(obs map[string]any) error {
	p, err := json.TFParser.Marshal(obs)
	if err != nil {
		return err
	}
	return json.TFParser.Unmarshal(p, &tr.Status.AtProvider)
}

// GetID returns ID of underlying Terraform resource of this TgwConnect
func (tr *TgwConnect) GetID() string {
	if tr.Status.AtProvider.ID == nil {
		return ""
	}
	return *tr.Status.AtProvider.ID
}

// GetParameters of this TgwConnect
func (tr *TgwConnect) GetParameters() (map[string]any, error) {
	p, err := json.TFParser.Marshal(tr.Spec.ForProvider)
	if err != nil {
		return nil, err
	}
	base := map[string]any{}
	return base, json.TFParser.Unmarshal(p, &base)
}

// SetParameters for this TgwConnect
func (tr *TgwConnect) SetParameters(params map[string]any) error {
	p, err := json.TFParser.Marshal(params)
	if err != nil {
		return err
	}
	return json.TFParser.Unmarshal(p, &tr.Spec.ForProvider)
}

// LateInitialize this TgwConnect using its observed tfState.
// returns True if there are any spec changes for the resource.
func (tr *TgwConnect) LateInitialize(attrs []byte) (bool, error) {
	params := &TgwConnectParameters{}
	if err := json.TFParser.Unmarshal(attrs, params); err != nil {
		return false, errors.Wrap(err, "failed to unmarshal Terraform state parameters for late-initialization")
	}
	opts := []resource.GenericLateInitializerOption{resource.WithZeroValueJSONOmitEmptyFilter(resource.CNameWildcard)}

	li := resource.NewGenericLateInitializer(opts...)
	return li.LateInitialize(&tr.Spec.ForProvider, params)
}

// GetTerraformSchemaVersion returns the associated Terraform schema version
func (tr *TgwConnect) GetTerraformSchemaVersion() int {
	return 0
}

// GetTerraformResourceType returns Terraform resource type for this TgwConnectPeer
func (mg *TgwConnectPeer) GetTerraformResourceType() string {
	return "aviatrix_aws_tgw_connect_peer"
}

// GetConnectionDetailsMapping for this TgwConnectPeer
func (tr *TgwConnectPeer) GetConnectionDetailsMapping() map[string]string {
	return nil
}

// GetObservation of this TgwConnectPeer
func (tr *TgwConnectPeer) GetObservation() (map[string]any, error) {
	o, err := json.TFParser.Marshal(tr.Status.AtProvider)
	if err != nil {
		return nil, err
	}
	base := map[string]any{}
	return base, json.TFParser.Unmarshal(o, &base)
}

// SetObservation for this TgwConnectPeer
func (tr *TgwConnectPeer) SetObservation(obs map[string]any) error {
	p, err := json.TFParser.Marshal(obs)
	if err != nil {
		return err
	}
	return json.TFParser.Unmarshal(p, &tr.Status.AtProvider)
}

// GetID returns ID of underlying Terraform resource of this TgwConnectPeer
func (tr *TgwConnectPeer) GetID() string {
	if tr.Status.AtProvider.ID == nil {
		return ""
	}
	return *tr.Status.AtProvider.ID
}

// GetParameters of this TgwConnectPeer
func (tr *TgwConnectPeer) GetParameters() (map[string]any, error) {
	p, err := json.TFParser.Marshal(tr.Spec.ForProvider)
	if err != nil {
		return nil, err
	}
	base := map[string]any{}
	return base, json.TFParser.Unmarshal(p, &base)
}

// SetParameters for this TgwConnectPeer
func (tr *TgwConnectPeer) SetParameters(params map[string]any) error {
	p, err := json.TFParser.Marshal(params)
	if err != nil {
		return err
	}
	return json.TFParser.Unmarshal(p, &tr.Spec.ForProvider)
}

// LateInitialize this TgwConnectPeer using its observed tfState.
// returns True if there are any spec changes for the resource.
func (tr *TgwConnectPeer) LateInitialize(attrs []byte) (bool, error) {
	params := &TgwConnectPeerParameters{}
	if err := json.TFParser.Unmarshal(attrs, params); err != nil {
		return false, errors.Wrap(err, "failed to unmarshal Terraform state parameters for late-initialization")
	}
	opts := []resource.GenericLateInitializerOption{resource.WithZeroValueJSONOmitEmptyFilter(resource.CNameWildcard)}

	li := resource.NewGenericLateInitializer(opts...)
	return li.LateInitialize(&tr.Spec.ForProvider, params)
}

// GetTerraformSchemaVersion returns the associated Terraform schema version
func (tr *TgwConnectPeer) GetTerraformSchemaVersion() int {
	return 0
}

// GetTerraformResourceType returns Terraform resource type for this TgwDirectconnect
func (mg *TgwDirectconnect) GetTerraformResourceType() string {
	return "aviatrix_aws_tgw_directconnect"
}

// GetConnectionDetailsMapping for this TgwDirectconnect
func (tr *TgwDirectconnect) GetConnectionDetailsMapping() map[string]string {
	return nil
}

// GetObservation of this TgwDirectconnect
func (tr *TgwDirectconnect) GetObservation() (map[string]any, error) {
	o, err := json.TFParser.Marshal(tr.Status.AtProvider)
	if err != nil {
		return nil, err
	}
	base := map[string]any{}
	return base, json.TFParser.Unmarshal(o, &base)
}

// SetObservation for this TgwDirectconnect
func (tr *TgwDirectconnect) SetObservation(obs map[string]any) error {
	p, err := json.TFParser.Marshal(obs)
	if err != nil {
		return err
	}
	return json.TFParser.Unmarshal(p, &tr.Status.AtProvider)
}

// GetID returns ID of underlying Terraform resource of this TgwDirectconnect
func (tr *TgwDirectconnect) GetID() string {
	if tr.Status.AtProvider.ID == nil {
		return ""
	}
	return *tr.Status.AtProvider.ID
}

// GetParameters of this TgwDirectconnect
func (tr *TgwDirectconnect) GetParameters() (map[string]any, error) {
	p, err := json.TFParser.Marshal(tr.Spec.ForProvider)
	if err != nil {
		return nil, err
	}
	base := map[string]any{}
	return base, json.TFParser.Unmarshal(p, &base)
}

// SetParameters for this TgwDirectconnect
func (tr *TgwDirectconnect) SetParameters(params map[string]any) error {
	p, err := json.TFParser.Marshal(params)
	if err != nil {
		return err
	}
	return json.TFParser.Unmarshal(p, &tr.Spec.ForProvider)
}

// LateInitialize this TgwDirectconnect using its observed tfState.
// returns True if there are any spec changes for the resource.
func (tr *TgwDirectconnect) LateInitialize(attrs []byte) (bool, error) {
	params := &TgwDirectconnectParameters{}
	if err := json.TFParser.Unmarshal(attrs, params); err != nil {
		return false, errors.Wrap(err, "failed to unmarshal Terraform state parameters for late-initialization")
	}
	opts := []resource.GenericLateInitializerOption{resource.WithZeroValueJSONOmitEmptyFilter(resource.CNameWildcard)}

	li := resource.NewGenericLateInitializer(opts...)
	return li.LateInitialize(&tr.Spec.ForProvider, params)
}

// GetTerraformSchemaVersion returns the associated Terraform schema version
func (tr *TgwDirectconnect) GetTerraformSchemaVersion() int {
	return 0
}

// GetTerraformResourceType returns Terraform resource type for this TgwIntraDomainInspection
func (mg *TgwIntraDomainInspection) GetTerraformResourceType() string {
	return "aviatrix_aws_tgw_intra_domain_inspection"
}

// GetConnectionDetailsMapping for this TgwIntraDomainInspection
func (tr *TgwIntraDomainInspection) GetConnectionDetailsMapping() map[string]string {
	return nil
}

// GetObservation of this TgwIntraDomainInspection
func (tr *TgwIntraDomainInspection) GetObservation() (map[string]any, error) {
	o, err := json.TFParser.Marshal(tr.Status.AtProvider)
	if err != nil {
		return nil, err
	}
	base := map[string]any{}
	return base, json.TFParser.Unmarshal(o, &base)
}

// SetObservation for this TgwIntraDomainInspection
func (tr *TgwIntraDomainInspection) SetObservation(obs map[string]any) error {
	p, err := json.TFParser.Marshal(obs)
	if err != nil {
		return err
	}
	return json.TFParser.Unmarshal(p, &tr.Status.AtProvider)
}

// GetID returns ID of underlying Terraform resource of this TgwIntraDomainInspection
func (tr *TgwIntraDomainInspection) GetID() string {
	if tr.Status.AtProvider.ID == nil {
		return ""
	}
	return *tr.Status.AtProvider.ID
}

// GetParameters of this TgwIntraDomainInspection
func (tr *TgwIntraDomainInspection) GetParameters() (map[string]any, error) {
	p, err := json.TFParser.Marshal(tr.Spec.ForProvider)
	if err != nil {
		return nil, err
	}
	base := map[string]any{}
	return base, json.TFParser.Unmarshal(p, &base)
}

// SetParameters for this TgwIntraDomainInspection
func (tr *TgwIntraDomainInspection) SetParameters(params map[string]any) error {
	p, err := json.TFParser.Marshal(params)
	if err != nil {
		return err
	}
	return json.TFParser.Unmarshal(p, &tr.Spec.ForProvider)
}

// LateInitialize this TgwIntraDomainInspection using its observed tfState.
// returns True if there are any spec changes for the resource.
func (tr *TgwIntraDomainInspection) LateInitialize(attrs []byte) (bool, error) {
	params := &TgwIntraDomainInspectionParameters{}
	if err := json.TFParser.Unmarshal(attrs, params); err != nil {
		return false, errors.Wrap(err, "failed to unmarshal Terraform state parameters for late-initialization")
	}
	opts := []resource.GenericLateInitializerOption{resource.WithZeroValueJSONOmitEmptyFilter(resource.CNameWildcard)}

	li := resource.NewGenericLateInitializer(opts...)
	return li.LateInitialize(&tr.Spec.ForProvider, params)
}

// GetTerraformSchemaVersion returns the associated Terraform schema version
func (tr *TgwIntraDomainInspection) GetTerraformSchemaVersion() int {
	return 0
}

// GetTerraformResourceType returns Terraform resource type for this TgwNetworkDomain
func (mg *TgwNetworkDomain) GetTerraformResourceType() string {
	return "aviatrix_aws_tgw_network_domain"
}

// GetConnectionDetailsMapping for this TgwNetworkDomain
func (tr *TgwNetworkDomain) GetConnectionDetailsMapping() map[string]string {
	return nil
}

// GetObservation of this TgwNetworkDomain
func (tr *TgwNetworkDomain) GetObservation() (map[string]any, error) {
	o, err := json.TFParser.Marshal(tr.Status.AtProvider)
	if err != nil {
		return nil, err
	}
	base := map[string]any{}
	return base, json.TFParser.Unmarshal(o, &base)
}

// SetObservation for this TgwNetworkDomain
func (tr *TgwNetworkDomain) SetObservation(obs map[string]any) error {
	p, err := json.TFParser.Marshal(obs)
	if err != nil {
		return err
	}
	return json.TFParser.Unmarshal(p, &tr.Status.AtProvider)
}

// GetID returns ID of underlying Terraform resource of this TgwNetworkDomain
func (tr *TgwNetworkDomain) GetID() string {
	if tr.Status.AtProvider.ID == nil {
		return ""
	}
	return *tr.Status.AtProvider.ID
}

// GetParameters of this TgwNetworkDomain
func (tr *TgwNetworkDomain) GetParameters() (map[string]any, error) {
	p, err := json.TFParser.Marshal(tr.Spec.ForProvider)
	if err != nil {
		return nil, err
	}
	base := map[string]any{}
	return base, json.TFParser.Unmarshal(p, &base)
}

// SetParameters for this TgwNetworkDomain
func (tr *TgwNetworkDomain) SetParameters(params map[string]any) error {
	p, err := json.TFParser.Marshal(params)
	if err != nil {
		return err
	}
	return json.TFParser.Unmarshal(p, &tr.Spec.ForProvider)
}

// LateInitialize this TgwNetworkDomain using its observed tfState.
// returns True if there are any spec changes for the resource.
func (tr *TgwNetworkDomain) LateInitialize(attrs []byte) (bool, error) {
	params := &TgwNetworkDomainParameters{}
	if err := json.TFParser.Unmarshal(attrs, params); err != nil {
		return false, errors.Wrap(err, "failed to unmarshal Terraform state parameters for late-initialization")
	}
	opts := []resource.GenericLateInitializerOption{resource.WithZeroValueJSONOmitEmptyFilter(resource.CNameWildcard)}

	li := resource.NewGenericLateInitializer(opts...)
	return li.LateInitialize(&tr.Spec.ForProvider, params)
}

// GetTerraformSchemaVersion returns the associated Terraform schema version
func (tr *TgwNetworkDomain) GetTerraformSchemaVersion() int {
	return 0
}

// GetTerraformResourceType returns Terraform resource type for this TgwPeering
func (mg *TgwPeering) GetTerraformResourceType() string {
	return "aviatrix_aws_tgw_peering"
}

// GetConnectionDetailsMapping for this TgwPeering
func (tr *TgwPeering) GetConnectionDetailsMapping() map[string]string {
	return nil
}

// GetObservation of this TgwPeering
func (tr *TgwPeering) GetObservation() (map[string]any, error) {
	o, err := json.TFParser.Marshal(tr.Status.AtProvider)
	if err != nil {
		return nil, err
	}
	base := map[string]any{}
	return base, json.TFParser.Unmarshal(o, &base)
}

// SetObservation for this TgwPeering
func (tr *TgwPeering) SetObservation(obs map[string]any) error {
	p, err := json.TFParser.Marshal(obs)
	if err != nil {
		return err
	}
	return json.TFParser.Unmarshal(p, &tr.Status.AtProvider)
}

// GetID returns ID of underlying Terraform resource of this TgwPeering
func (tr *TgwPeering) GetID() string {
	if tr.Status.AtProvider.ID == nil {
		return ""
	}
	return *tr.Status.AtProvider.ID
}

// GetParameters of this TgwPeering
func (tr *TgwPeering) GetParameters() (map[string]any, error) {
	p, err := json.TFParser.Marshal(tr.Spec.ForProvider)
	if err != nil {
		return nil, err
	}
	base := map[string]any{}
	return base, json.TFParser.Unmarshal(p, &base)
}

// SetParameters for this TgwPeering
func (tr *TgwPeering) SetParameters(params map[string]any) error {
	p, err := json.TFParser.Marshal(params)
	if err != nil {
		return err
	}
	return json.TFParser.Unmarshal(p, &tr.Spec.ForProvider)
}

// LateInitialize this TgwPeering using its observed tfState.
// returns True if there are any spec changes for the resource.
func (tr *TgwPeering) LateInitialize(attrs []byte) (bool, error) {
	params := &TgwPeeringParameters{}
	if err := json.TFParser.Unmarshal(attrs, params); err != nil {
		return false, errors.Wrap(err, "failed to unmarshal Terraform state parameters for late-initialization")
	}
	opts := []resource.GenericLateInitializerOption{resource.WithZeroValueJSONOmitEmptyFilter(resource.CNameWildcard)}

	li := resource.NewGenericLateInitializer(opts...)
	return li.LateInitialize(&tr.Spec.ForProvider, params)
}

// GetTerraformSchemaVersion returns the associated Terraform schema version
func (tr *TgwPeering) GetTerraformSchemaVersion() int {
	return 0
}

// GetTerraformResourceType returns Terraform resource type for this TgwPeeringDomainConn
func (mg *TgwPeeringDomainConn) GetTerraformResourceType() string {
	return "aviatrix_aws_tgw_peering_domain_conn"
}

// GetConnectionDetailsMapping for this TgwPeeringDomainConn
func (tr *TgwPeeringDomainConn) GetConnectionDetailsMapping() map[string]string {
	return nil
}

// GetObservation of this TgwPeeringDomainConn
func (tr *TgwPeeringDomainConn) GetObservation() (map[string]any, error) {
	o, err := json.TFParser.Marshal(tr.Status.AtProvider)
	if err != nil {
		return nil, err
	}
	base := map[string]any{}
	return base, json.TFParser.Unmarshal(o, &base)
}

// SetObservation for this TgwPeeringDomainConn
func (tr *TgwPeeringDomainConn) SetObservation(obs map[string]any) error {
	p, err := json.TFParser.Marshal(obs)
	if err != nil {
		return err
	}
	return json.TFParser.Unmarshal(p, &tr.Status.AtProvider)
}

// GetID returns ID of underlying Terraform resource of this TgwPeeringDomainConn
func (tr *TgwPeeringDomainConn) GetID() string {
	if tr.Status.AtProvider.ID == nil {
		return ""
	}
	return *tr.Status.AtProvider.ID
}

// GetParameters of this TgwPeeringDomainConn
func (tr *TgwPeeringDomainConn) GetParameters() (map[string]any, error) {
	p, err := json.TFParser.Marshal(tr.Spec.ForProvider)
	if err != nil {
		return nil, err
	}
	base := map[string]any{}
	return base, json.TFParser.Unmarshal(p, &base)
}

// SetParameters for this TgwPeeringDomainConn
func (tr *TgwPeeringDomainConn) SetParameters(params map[string]any) error {
	p, err := json.TFParser.Marshal(params)
	if err != nil {
		return err
	}
	return json.TFParser.Unmarshal(p, &tr.Spec.ForProvider)
}

// LateInitialize this TgwPeeringDomainConn using its observed tfState.
// returns True if there are any spec changes for the resource.
func (tr *TgwPeeringDomainConn) LateInitialize(attrs []byte) (bool, error) {
	params := &TgwPeeringDomainConnParameters{}
	if err := json.TFParser.Unmarshal(attrs, params); err != nil {
		return false, errors.Wrap(err, "failed to unmarshal Terraform state parameters for late-initialization")
	}
	opts := []resource.GenericLateInitializerOption{resource.WithZeroValueJSONOmitEmptyFilter(resource.CNameWildcard)}

	li := resource.NewGenericLateInitializer(opts...)
	return li.LateInitialize(&tr.Spec.ForProvider, params)
}

// GetTerraformSchemaVersion returns the associated Terraform schema version
func (tr *TgwPeeringDomainConn) GetTerraformSchemaVersion() int {
	return 0
}

// GetTerraformResourceType returns Terraform resource type for this TgwTransitGatewayAttachment
func (mg *TgwTransitGatewayAttachment) GetTerraformResourceType() string {
	return "aviatrix_aws_tgw_transit_gateway_attachment"
}

// GetConnectionDetailsMapping for this TgwTransitGatewayAttachment
func (tr *TgwTransitGatewayAttachment) GetConnectionDetailsMapping() map[string]string {
	return nil
}

// GetObservation of this TgwTransitGatewayAttachment
func (tr *TgwTransitGatewayAttachment) GetObservation() (map[string]any, error) {
	o, err := json.TFParser.Marshal(tr.Status.AtProvider)
	if err != nil {
		return nil, err
	}
	base := map[string]any{}
	return base, json.TFParser.Unmarshal(o, &base)
}

// SetObservation for this TgwTransitGatewayAttachment
func (tr *TgwTransitGatewayAttachment) SetObservation(obs map[string]any) error {
	p, err := json.TFParser.Marshal(obs)
	if err != nil {
		return err
	}
	return json.TFParser.Unmarshal(p, &tr.Status.AtProvider)
}

// GetID returns ID of underlying Terraform resource of this TgwTransitGatewayAttachment
func (tr *TgwTransitGatewayAttachment) GetID() string {
	if tr.Status.AtProvider.ID == nil {
		return ""
	}
	return *tr.Status.AtProvider.ID
}

// GetParameters of this TgwTransitGatewayAttachment
func (tr *TgwTransitGatewayAttachment) GetParameters() (map[string]any, error) {
	p, err := json.TFParser.Marshal(tr.Spec.ForProvider)
	if err != nil {
		return nil, err
	}
	base := map[string]any{}
	return base, json.TFParser.Unmarshal(p, &base)
}

// SetParameters for this TgwTransitGatewayAttachment
func (tr *TgwTransitGatewayAttachment) SetParameters(params map[string]any) error {
	p, err := json.TFParser.Marshal(params)
	if err != nil {
		return err
	}
	return json.TFParser.Unmarshal(p, &tr.Spec.ForProvider)
}

// LateInitialize this TgwTransitGatewayAttachment using its observed tfState.
// returns True if there are any spec changes for the resource.
func (tr *TgwTransitGatewayAttachment) LateInitialize(attrs []byte) (bool, error) {
	params := &TgwTransitGatewayAttachmentParameters{}
	if err := json.TFParser.Unmarshal(attrs, params); err != nil {
		return false, errors.Wrap(err, "failed to unmarshal Terraform state parameters for late-initialization")
	}
	opts := []resource.GenericLateInitializerOption{resource.WithZeroValueJSONOmitEmptyFilter(resource.CNameWildcard)}

	li := resource.NewGenericLateInitializer(opts...)
	return li.LateInitialize(&tr.Spec.ForProvider, params)
}

// GetTerraformSchemaVersion returns the associated Terraform schema version
func (tr *TgwTransitGatewayAttachment) GetTerraformSchemaVersion() int {
	return 0
}

// GetTerraformResourceType returns Terraform resource type for this TgwVPCAttachment
func (mg *TgwVPCAttachment) GetTerraformResourceType() string {
	return "aviatrix_aws_tgw_vpc_attachment"
}

// GetConnectionDetailsMapping for this TgwVPCAttachment
func (tr *TgwVPCAttachment) GetConnectionDetailsMapping() map[string]string {
	return nil
}

// GetObservation of this TgwVPCAttachment
func (tr *TgwVPCAttachment) GetObservation() (map[string]any, error) {
	o, err := json.TFParser.Marshal(tr.Status.AtProvider)
	if err != nil {
		return nil, err
	}
	base := map[string]any{}
	return base, json.TFParser.Unmarshal(o, &base)
}

// SetObservation for this TgwVPCAttachment
func (tr *TgwVPCAttachment) SetObservation(obs map[string]any) error {
	p, err := json.TFParser.Marshal(obs)
	if err != nil {
		return err
	}
	return json.TFParser.Unmarshal(p, &tr.Status.AtProvider)
}

// GetID returns ID of underlying Terraform resource of this TgwVPCAttachment
func (tr *TgwVPCAttachment) GetID() string {
	if tr.Status.AtProvider.ID == nil {
		return ""
	}
	return *tr.Status.AtProvider.ID
}

// GetParameters of this TgwVPCAttachment
func (tr *TgwVPCAttachment) GetParameters() (map[string]any, error) {
	p, err := json.TFParser.Marshal(tr.Spec.ForProvider)
	if err != nil {
		return nil, err
	}
	base := map[string]any{}
	return base, json.TFParser.Unmarshal(p, &base)
}

// SetParameters for this TgwVPCAttachment
func (tr *TgwVPCAttachment) SetParameters(params map[string]any) error {
	p, err := json.TFParser.Marshal(params)
	if err != nil {
		return err
	}
	return json.TFParser.Unmarshal(p, &tr.Spec.ForProvider)
}

// LateInitialize this TgwVPCAttachment using its observed tfState.
// returns True if there are any spec changes for the resource.
func (tr *TgwVPCAttachment) LateInitialize(attrs []byte) (bool, error) {
	params := &TgwVPCAttachmentParameters{}
	if err := json.TFParser.Unmarshal(attrs, params); err != nil {
		return false, errors.Wrap(err, "failed to unmarshal Terraform state parameters for late-initialization")
	}
	opts := []resource.GenericLateInitializerOption{resource.WithZeroValueJSONOmitEmptyFilter(resource.CNameWildcard)}

	li := resource.NewGenericLateInitializer(opts...)
	return li.LateInitialize(&tr.Spec.ForProvider, params)
}

// GetTerraformSchemaVersion returns the associated Terraform schema version
func (tr *TgwVPCAttachment) GetTerraformSchemaVersion() int {
	return 0
}

// GetTerraformResourceType returns Terraform resource type for this TgwVPNConn
func (mg *TgwVPNConn) GetTerraformResourceType() string {
	return "aviatrix_aws_tgw_vpn_conn"
}

// GetConnectionDetailsMapping for this TgwVPNConn
func (tr *TgwVPNConn) GetConnectionDetailsMapping() map[string]string {
	return map[string]string{"pre_shared_key_tun_1": "spec.forProvider.preSharedKeyTun1SecretRef", "pre_shared_key_tun_2": "spec.forProvider.preSharedKeyTun2SecretRef"}
}

// GetObservation of this TgwVPNConn
func (tr *TgwVPNConn) GetObservation() (map[string]any, error) {
	o, err := json.TFParser.Marshal(tr.Status.AtProvider)
	if err != nil {
		return nil, err
	}
	base := map[string]any{}
	return base, json.TFParser.Unmarshal(o, &base)
}

// SetObservation for this TgwVPNConn
func (tr *TgwVPNConn) SetObservation(obs map[string]any) error {
	p, err := json.TFParser.Marshal(obs)
	if err != nil {
		return err
	}
	return json.TFParser.Unmarshal(p, &tr.Status.AtProvider)
}

// GetID returns ID of underlying Terraform resource of this TgwVPNConn
func (tr *TgwVPNConn) GetID() string {
	if tr.Status.AtProvider.ID == nil {
		return ""
	}
	return *tr.Status.AtProvider.ID
}

// GetParameters of this TgwVPNConn
func (tr *TgwVPNConn) GetParameters() (map[string]any, error) {
	p, err := json.TFParser.Marshal(tr.Spec.ForProvider)
	if err != nil {
		return nil, err
	}
	base := map[string]any{}
	return base, json.TFParser.Unmarshal(p, &base)
}

// SetParameters for this TgwVPNConn
func (tr *TgwVPNConn) SetParameters(params map[string]any) error {
	p, err := json.TFParser.Marshal(params)
	if err != nil {
		return err
	}
	return json.TFParser.Unmarshal(p, &tr.Spec.ForProvider)
}

// LateInitialize this TgwVPNConn using its observed tfState.
// returns True if there are any spec changes for the resource.
func (tr *TgwVPNConn) LateInitialize(attrs []byte) (bool, error) {
	params := &TgwVPNConnParameters{}
	if err := json.TFParser.Unmarshal(attrs, params); err != nil {
		return false, errors.Wrap(err, "failed to unmarshal Terraform state parameters for late-initialization")
	}
	opts := []resource.GenericLateInitializerOption{resource.WithZeroValueJSONOmitEmptyFilter(resource.CNameWildcard)}

	li := resource.NewGenericLateInitializer(opts...)
	return li.LateInitialize(&tr.Spec.ForProvider, params)
}

// GetTerraformSchemaVersion returns the associated Terraform schema version
func (tr *TgwVPNConn) GetTerraformSchemaVersion() int {
	return 0
}
