/*
Copyright 2022 Upbound Inc.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type TgwPeeringDomainConnObservation struct {
	ID *string `json:"id,omitempty" tf:"id,omitempty"`
}

type TgwPeeringDomainConnParameters struct {

	// The name of the source domain to make a connection.
	// +kubebuilder:validation:Required
	DomainName1 *string `json:"domainName1" tf:"domain_name1,omitempty"`

	// The name of the destination domain to make a connection.
	// +kubebuilder:validation:Required
	DomainName2 *string `json:"domainName2" tf:"domain_name2,omitempty"`

	// The AWS tgw name of the source domain to make a connection.
	// +kubebuilder:validation:Required
	TgwName1 *string `json:"tgwName1" tf:"tgw_name1,omitempty"`

	// The AWS tgw name of the destination domain to make a connection.
	// +kubebuilder:validation:Required
	TgwName2 *string `json:"tgwName2" tf:"tgw_name2,omitempty"`
}

// TgwPeeringDomainConnSpec defines the desired state of TgwPeeringDomainConn
type TgwPeeringDomainConnSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     TgwPeeringDomainConnParameters `json:"forProvider"`
}

// TgwPeeringDomainConnStatus defines the observed state of TgwPeeringDomainConn.
type TgwPeeringDomainConnStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        TgwPeeringDomainConnObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true

// TgwPeeringDomainConn is the Schema for the TgwPeeringDomainConns API. <no value>
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,aviatrix}
type TgwPeeringDomainConn struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              TgwPeeringDomainConnSpec   `json:"spec"`
	Status            TgwPeeringDomainConnStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// TgwPeeringDomainConnList contains a list of TgwPeeringDomainConns
type TgwPeeringDomainConnList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []TgwPeeringDomainConn `json:"items"`
}

// Repository type metadata.
var (
	TgwPeeringDomainConn_Kind             = "TgwPeeringDomainConn"
	TgwPeeringDomainConn_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: TgwPeeringDomainConn_Kind}.String()
	TgwPeeringDomainConn_KindAPIVersion   = TgwPeeringDomainConn_Kind + "." + CRDGroupVersion.String()
	TgwPeeringDomainConn_GroupVersionKind = CRDGroupVersion.WithKind(TgwPeeringDomainConn_Kind)
)

func init() {
	SchemeBuilder.Register(&TgwPeeringDomainConn{}, &TgwPeeringDomainConnList{})
}
