/*
Copyright 2022 Upbound Inc.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type TgwConnectPeerObservation struct {

	// Connect Peer ID.
	ConnectPeerID *string `json:"connectPeerId,omitempty" tf:"connect_peer_id,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`
}

type TgwConnectPeerParameters struct {

	// Set of BGP Inside CIDR Blocks.
	// +kubebuilder:validation:Required
	BGPInsideCidrs []*string `json:"bgpInsideCidrs" tf:"bgp_inside_cidrs,omitempty"`

	// Connect Attachment ID.
	// +kubebuilder:validation:Required
	ConnectAttachmentID *string `json:"connectAttachmentId" tf:"connect_attachment_id,omitempty"`

	// Connect Peer Name.
	// +kubebuilder:validation:Required
	ConnectPeerName *string `json:"connectPeerName" tf:"connect_peer_name,omitempty"`

	// AWS TGW Connect connection name.
	// +kubebuilder:validation:Required
	ConnectionName *string `json:"connectionName" tf:"connection_name,omitempty"`

	// Peer AS Number.
	// +kubebuilder:validation:Required
	PeerAsNumber *string `json:"peerAsNumber" tf:"peer_as_number,omitempty"`

	// Peer GRE IP Address.
	// +kubebuilder:validation:Required
	PeerGreAddress *string `json:"peerGreAddress" tf:"peer_gre_address,omitempty"`

	// AWS TGW GRE IP Address.
	// +kubebuilder:validation:Optional
	TgwGreAddress *string `json:"tgwGreAddress,omitempty" tf:"tgw_gre_address,omitempty"`

	// AWS TGW Name.
	// +kubebuilder:validation:Required
	TgwName *string `json:"tgwName" tf:"tgw_name,omitempty"`
}

// TgwConnectPeerSpec defines the desired state of TgwConnectPeer
type TgwConnectPeerSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     TgwConnectPeerParameters `json:"forProvider"`
}

// TgwConnectPeerStatus defines the observed state of TgwConnectPeer.
type TgwConnectPeerStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        TgwConnectPeerObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true

// TgwConnectPeer is the Schema for the TgwConnectPeers API. <no value>
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,aviatrix}
type TgwConnectPeer struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              TgwConnectPeerSpec   `json:"spec"`
	Status            TgwConnectPeerStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// TgwConnectPeerList contains a list of TgwConnectPeers
type TgwConnectPeerList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []TgwConnectPeer `json:"items"`
}

// Repository type metadata.
var (
	TgwConnectPeer_Kind             = "TgwConnectPeer"
	TgwConnectPeer_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: TgwConnectPeer_Kind}.String()
	TgwConnectPeer_KindAPIVersion   = TgwConnectPeer_Kind + "." + CRDGroupVersion.String()
	TgwConnectPeer_GroupVersionKind = CRDGroupVersion.WithKind(TgwConnectPeer_Kind)
)

func init() {
	SchemeBuilder.Register(&TgwConnectPeer{}, &TgwConnectPeerList{})
}
