/*
Copyright 2022 Upbound Inc.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type TgwPeeringObservation struct {
	ID *string `json:"id,omitempty" tf:"id,omitempty"`
}

type TgwPeeringParameters struct {

	// Name of the first AWS tgw to make a peer pair.
	// +kubebuilder:validation:Required
	TgwName1 *string `json:"tgwName1" tf:"tgw_name1,omitempty"`

	// Name of the second AWS tgw to make a peer pair.
	// +kubebuilder:validation:Required
	TgwName2 *string `json:"tgwName2" tf:"tgw_name2,omitempty"`
}

// TgwPeeringSpec defines the desired state of TgwPeering
type TgwPeeringSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     TgwPeeringParameters `json:"forProvider"`
}

// TgwPeeringStatus defines the observed state of TgwPeering.
type TgwPeeringStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        TgwPeeringObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true

// TgwPeering is the Schema for the TgwPeerings API. <no value>
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,aviatrix}
type TgwPeering struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              TgwPeeringSpec   `json:"spec"`
	Status            TgwPeeringStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// TgwPeeringList contains a list of TgwPeerings
type TgwPeeringList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []TgwPeering `json:"items"`
}

// Repository type metadata.
var (
	TgwPeering_Kind             = "TgwPeering"
	TgwPeering_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: TgwPeering_Kind}.String()
	TgwPeering_KindAPIVersion   = TgwPeering_Kind + "." + CRDGroupVersion.String()
	TgwPeering_GroupVersionKind = CRDGroupVersion.WithKind(TgwPeering_Kind)
)

func init() {
	SchemeBuilder.Register(&TgwPeering{}, &TgwPeeringList{})
}
