/*
Copyright 2022 Upbound Inc.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type TgwNetworkDomainObservation struct {
	ID *string `json:"id,omitempty" tf:"id,omitempty"`
}

type TgwNetworkDomainParameters struct {

	// Set to true if the network domain is an aviatrix firewall domain.
	// +kubebuilder:validation:Optional
	AviatrixFirewall *bool `json:"aviatrixFirewall,omitempty" tf:"aviatrix_firewall,omitempty"`

	// Set to true if the network domain is a native egress domain.
	// +kubebuilder:validation:Optional
	NativeEgress *bool `json:"nativeEgress,omitempty" tf:"native_egress,omitempty"`

	// Set to true if the network domain is a native firewall domain.
	// +kubebuilder:validation:Optional
	NativeFirewall *bool `json:"nativeFirewall,omitempty" tf:"native_firewall,omitempty"`

	// AWS TGW name.
	// +kubebuilder:validation:Required
	TgwName *string `json:"tgwName" tf:"tgw_name,omitempty"`
}

// TgwNetworkDomainSpec defines the desired state of TgwNetworkDomain
type TgwNetworkDomainSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     TgwNetworkDomainParameters `json:"forProvider"`
}

// TgwNetworkDomainStatus defines the observed state of TgwNetworkDomain.
type TgwNetworkDomainStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        TgwNetworkDomainObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true

// TgwNetworkDomain is the Schema for the TgwNetworkDomains API. <no value>
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,aviatrix}
type TgwNetworkDomain struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              TgwNetworkDomainSpec   `json:"spec"`
	Status            TgwNetworkDomainStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// TgwNetworkDomainList contains a list of TgwNetworkDomains
type TgwNetworkDomainList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []TgwNetworkDomain `json:"items"`
}

// Repository type metadata.
var (
	TgwNetworkDomain_Kind             = "TgwNetworkDomain"
	TgwNetworkDomain_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: TgwNetworkDomain_Kind}.String()
	TgwNetworkDomain_KindAPIVersion   = TgwNetworkDomain_Kind + "." + CRDGroupVersion.String()
	TgwNetworkDomain_GroupVersionKind = CRDGroupVersion.WithKind(TgwNetworkDomain_Kind)
)

func init() {
	SchemeBuilder.Register(&TgwNetworkDomain{}, &TgwNetworkDomainList{})
}
