/*
Copyright 2022 Upbound Inc.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type TgwIntraDomainInspectionObservation struct {
	ID *string `json:"id,omitempty" tf:"id,omitempty"`
}

type TgwIntraDomainInspectionParameters struct {

	// Firewall domain name.
	// +kubebuilder:validation:Required
	FirewallDomainName *string `json:"firewallDomainName" tf:"firewall_domain_name,omitempty"`

	// AWS TGW name.
	// +kubebuilder:validation:Required
	TgwName *string `json:"tgwName" tf:"tgw_name,omitempty"`
}

// TgwIntraDomainInspectionSpec defines the desired state of TgwIntraDomainInspection
type TgwIntraDomainInspectionSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     TgwIntraDomainInspectionParameters `json:"forProvider"`
}

// TgwIntraDomainInspectionStatus defines the observed state of TgwIntraDomainInspection.
type TgwIntraDomainInspectionStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        TgwIntraDomainInspectionObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true

// TgwIntraDomainInspection is the Schema for the TgwIntraDomainInspections API. <no value>
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,aviatrix}
type TgwIntraDomainInspection struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              TgwIntraDomainInspectionSpec   `json:"spec"`
	Status            TgwIntraDomainInspectionStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// TgwIntraDomainInspectionList contains a list of TgwIntraDomainInspections
type TgwIntraDomainInspectionList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []TgwIntraDomainInspection `json:"items"`
}

// Repository type metadata.
var (
	TgwIntraDomainInspection_Kind             = "TgwIntraDomainInspection"
	TgwIntraDomainInspection_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: TgwIntraDomainInspection_Kind}.String()
	TgwIntraDomainInspection_KindAPIVersion   = TgwIntraDomainInspection_Kind + "." + CRDGroupVersion.String()
	TgwIntraDomainInspection_GroupVersionKind = CRDGroupVersion.WithKind(TgwIntraDomainInspection_Kind)
)

func init() {
	SchemeBuilder.Register(&TgwIntraDomainInspection{}, &TgwIntraDomainInspectionList{})
}
