//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2022 Upbound Inc.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FirewallingIntraVPC) DeepCopyInto(out *FirewallingIntraVPC) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FirewallingIntraVPC.
func (in *FirewallingIntraVPC) DeepCopy() *FirewallingIntraVPC {
	if in == nil {
		return nil
	}
	out := new(FirewallingIntraVPC)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *FirewallingIntraVPC) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FirewallingIntraVPCList) DeepCopyInto(out *FirewallingIntraVPCList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]FirewallingIntraVPC, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FirewallingIntraVPCList.
func (in *FirewallingIntraVPCList) DeepCopy() *FirewallingIntraVPCList {
	if in == nil {
		return nil
	}
	out := new(FirewallingIntraVPCList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *FirewallingIntraVPCList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FirewallingIntraVPCObservation) DeepCopyInto(out *FirewallingIntraVPCObservation) {
	*out = *in
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FirewallingIntraVPCObservation.
func (in *FirewallingIntraVPCObservation) DeepCopy() *FirewallingIntraVPCObservation {
	if in == nil {
		return nil
	}
	out := new(FirewallingIntraVPCObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FirewallingIntraVPCParameters) DeepCopyInto(out *FirewallingIntraVPCParameters) {
	*out = *in
	if in.Vpcs != nil {
		in, out := &in.Vpcs, &out.Vpcs
		*out = make([]VpcsParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FirewallingIntraVPCParameters.
func (in *FirewallingIntraVPCParameters) DeepCopy() *FirewallingIntraVPCParameters {
	if in == nil {
		return nil
	}
	out := new(FirewallingIntraVPCParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FirewallingIntraVPCSpec) DeepCopyInto(out *FirewallingIntraVPCSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FirewallingIntraVPCSpec.
func (in *FirewallingIntraVPCSpec) DeepCopy() *FirewallingIntraVPCSpec {
	if in == nil {
		return nil
	}
	out := new(FirewallingIntraVPCSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FirewallingIntraVPCStatus) DeepCopyInto(out *FirewallingIntraVPCStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FirewallingIntraVPCStatus.
func (in *FirewallingIntraVPCStatus) DeepCopy() *FirewallingIntraVPCStatus {
	if in == nil {
		return nil
	}
	out := new(FirewallingIntraVPCStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VpcsObservation) DeepCopyInto(out *VpcsObservation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VpcsObservation.
func (in *VpcsObservation) DeepCopy() *VpcsObservation {
	if in == nil {
		return nil
	}
	out := new(VpcsObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VpcsParameters) DeepCopyInto(out *VpcsParameters) {
	*out = *in
	if in.AccountName != nil {
		in, out := &in.AccountName, &out.AccountName
		*out = new(string)
		**out = **in
	}
	if in.Region != nil {
		in, out := &in.Region, &out.Region
		*out = new(string)
		**out = **in
	}
	if in.VPCID != nil {
		in, out := &in.VPCID, &out.VPCID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VpcsParameters.
func (in *VpcsParameters) DeepCopy() *VpcsParameters {
	if in == nil {
		return nil
	}
	out := new(VpcsParameters)
	in.DeepCopyInto(out)
	return out
}
