/*
Copyright 2022 Upbound Inc.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type PingObservation struct {
	ID *string `json:"id,omitempty" tf:"id,omitempty"`
}

type PingParameters struct {

	// IP Address to ping.
	// +kubebuilder:validation:Required
	IPAddress *string `json:"ipAddress" tf:"ip_address,omitempty"`

	// Interval between pings in seconds.
	// +kubebuilder:validation:Required
	Interval *float64 `json:"interval" tf:"interval,omitempty"`
}

// PingSpec defines the desired state of Ping
type PingSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     PingParameters `json:"forProvider"`
}

// PingStatus defines the observed state of Ping.
type PingStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        PingObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true

// Ping is the Schema for the Pings API. <no value>
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,aviatrix}
type Ping struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              PingSpec   `json:"spec"`
	Status            PingStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// PingList contains a list of Pings
type PingList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Ping `json:"items"`
}

// Repository type metadata.
var (
	Ping_Kind             = "Ping"
	Ping_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Ping_Kind}.String()
	Ping_KindAPIVersion   = Ping_Kind + "." + CRDGroupVersion.String()
	Ping_GroupVersionKind = CRDGroupVersion.WithKind(Ping_Kind)
)

func init() {
	SchemeBuilder.Register(&Ping{}, &PingList{})
}
